development:
  adapter: postgresql
  host: localhost
  username: sample_app
  password: postgres
  database: app-dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  username: sample_app
  password: postgres
  database: sample_app-test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  username: sample_app
  password: postgres
  database: dample_app-prod
  pool: 5
  timeout: 5000